# This workflow will build and upload binaries when a release is created

name: Push to choco

on:
  release:
    types: [unpublished]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Show env vars
        run: >-
          Get-ChildItem Env:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      #      - name: Prepare for CI and run tests
      #        run: make ci

      - name: Install choco
        run: >-
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Vendor packages
        run: go mod vendor

      - name: Build gossamer3 and push to choco
        run: .\choco\deploy.ps1
