# This workflow will build and upload binaries when a release is created

name: Push to choco

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install packages
        run: make mod

      - name: Run tests
        run: make ci

#      - name: Build gossamer3 and push to choco
#        run: .\choco\deploy.ps1
